name: mobileapp
description: This is the controller from the mobile app to the embedded arduino car.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_blue: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
